import {
	MAIN,
	CREATE_POST,
	POSTS,
	CREATE_CATEGORY,
	MANAGE_POSTS,
	MANAGE_CATEGORY,
} from './tabs';

export default {
	MAIN: `/${MAIN}`,
	CREATE_POST: `/${CREATE_POST}`,
	POSTS: `/${POSTS}`,
	CREATE_CATEGORY: `/${CREATE_CATEGORY}`,
	MANAGE_POSTS: `/${MANAGE_POSTS}`,
	MANAGE_CATEGORY: `/${MANAGE_CATEGORY}`
};
