import {
	RELATIVE_PATH,

	MAIN,
	CREATE_POST,
	POSTS,
	CREATE_CATEGORY,
	MANAGE_POSTS,
	MANAGE_CATEGORY,
} from './tabs';

export default {
	MAIN: `/${RELATIVE_PATH}/${MAIN}`,
	CREATE_POST: `/${RELATIVE_PATH}/${CREATE_POST}`,
	POSTS: `/${RELATIVE_PATH}/${POSTS}`,
	CREATE_CATEGORY: `/${RELATIVE_PATH}/${CREATE_CATEGORY}`,
	MANAGE_POSTS: `/${RELATIVE_PATH}/${MANAGE_POSTS}`,
	MANAGE_CATEGORY: `/${RELATIVE_PATH}/${MANAGE_CATEGORY}`
};
