export default {
	SHOW_ALL_POSTS: 'SHOW_ALL_POSTS',
	SHOW_ALL_CATEGORIES: 'SHOW_ALL_CATEGORIES',

	GET_POST_BY_ID: 'SHOW_POST_BY_ID',

	CREATE_POST: 'CREATE_POST',
	DELETE_POST: 'DELETE_POST',

	CREATE_CATEGORY: 'CREATE_CATEGORY',
	DELETE_CATEGORY: 'DELETE_CATEGORY',

	LIKE_POST: 'LIKE_POST',
	DISLIKE_POST: 'DISLIKE_POST',
};
