export default {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_POSTS_BY_CATEGORY: 'SHOW_POSTS_BY_CATEGORY',
	GET_POST_BY_ID: 'SHOW_POST_BY_ID',

	CREATE_POST: 'CREATE_POST',
	DELETE_POST: 'DELETE_POST',

	CREATE_CATEGORY: 'CREATE_CATEGORY',
	DELETE_CATEGORY: 'DELETE_CATEGORY'
};
