export const postActions = {
	SHOW_ALL_POSTS: 'SHOW_ALL_POSTS',

	CREATE_POST: 'CREATE_POST',
	DELETE_POST: 'DELETE_POST',

	LIKE_POST: 'LIKE_POST',
	DISLIKE_POST: 'DISLIKE_POST',

	FETCHING_POSTS: 'FETCHING_POSTS',
	FETCHING_POSTS_SUCCEDED: 'FETCHING_POSTS_SUCCEDED',
	FETCHING_POSTS_FAILED: 'FETCHING_POSTS_FAILED',
};

export const categoryActions = {
	SHOW_ALL_CATEGORIES: 'SHOW_ALL_CATEGORIES',
	SWITCH_CURR_CATEGORY: 'SWITCH_CURR_CATEGORY',

	GET_POST_BY_ID: 'SHOW_POST_BY_ID',

	CREATE_CATEGORY: 'CREATE_CATEGORY',
	DELETE_CATEGORY: 'DELETE_CATEGORY',

	FETCHING_CATEGORIES: 'FETCHING_CATEGORIES',
	FETCHING_CATEGORIES_SUCCEDED: 'FETCHING_CATEGORIES_SUCCEDED',
	FETCHING_CATEGORIES_FAILED: 'FETCHING_CATEGORIES_FAILED',
};
